### ISSUE TITLE
gulp images

### ISSUE THREAD

**Issue by vinbanton** [epilande/gulp-jade-sass-static#1]
this boilerplate works really well for the scss and jade, thanks!

when i create a folder called "images" under "assets" and put in some images, they don't get processed and copied to the public folder by gulp. 
i can't figure out why (also im new to gulp...). any idea?

the scss: 
header {
background-image: url(../images/surf.jpg);
}

Thanks in advance,
Vin

![terminal surf](https://cloud.githubusercontent.com/assets/8211481/9396302/25d662f2-4794-11e5-9c00-c85f1eedc164.jpg)

**Comment by epilande** [comment]
I just tried it & it worked for me. 
Have you tried restarting your gulp process?

**Comment by vinbanton** [comment]
I restarted the gulp process and it works!
Thanks! :)
